// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/talos/hub/v1/hub.proto

package hubpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceAppId   string                 `protobuf:"bytes,1,opt,name=source_app_id,json=sourceAppId,proto3" json:"source_app_id,omitempty"`
	TargetAppId   string                 `protobuf:"bytes,2,opt,name=target_app_id,json=targetAppId,proto3" json:"target_app_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	RequestId     string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_proto_talos_hub_v1_hub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_talos_hub_v1_hub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_proto_talos_hub_v1_hub_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetSourceAppId() string {
	if x != nil {
		return x.SourceAppId
	}
	return ""
}

func (x *Message) GetTargetAppId() string {
	if x != nil {
		return x.TargetAppId
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RouteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_api_proto_talos_hub_v1_hub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_talos_hub_v1_hub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_talos_hub_v1_hub_proto_rawDescGZIP(), []int{1}
}

func (x *RouteRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type RouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_api_proto_talos_hub_v1_hub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_talos_hub_v1_hub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_talos_hub_v1_hub_proto_rawDescGZIP(), []int{2}
}

func (x *RouteResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *RouteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BroadcastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_api_proto_talos_hub_v1_hub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_talos_hub_v1_hub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_talos_hub_v1_hub_proto_rawDescGZIP(), []int{3}
}

func (x *BroadcastRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type BroadcastResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RecipientCount int32                  `protobuf:"varint,1,opt,name=recipient_count,json=recipientCount,proto3" json:"recipient_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_api_proto_talos_hub_v1_hub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_talos_hub_v1_hub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_talos_hub_v1_hub_proto_rawDescGZIP(), []int{4}
}

func (x *BroadcastResponse) GetRecipientCount() int32 {
	if x != nil {
		return x.RecipientCount
	}
	return 0
}

var File_api_proto_talos_hub_v1_hub_proto protoreflect.FileDescriptor

const file_api_proto_talos_hub_v1_hub_proto_rawDesc = "" +
	"\n" +
	" api/proto/talos/hub/v1/hub.proto\x12\ftalos.hub.v1\"\x9e\x01\n" +
	"\aMessage\x12\"\n" +
	"\rsource_app_id\x18\x01 \x01(\tR\vsourceAppId\x12\"\n" +
	"\rtarget_app_id\x18\x02 \x01(\tR\vtargetAppId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\"?\n" +
	"\fRouteRequest\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.talos.hub.v1.MessageR\amessage\"V\n" +
	"\rRouteResponse\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.talos.hub.v1.MessageR\amessage\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"C\n" +
	"\x10BroadcastRequest\x12/\n" +
	"\amessage\x18\x01 \x01(\v2\x15.talos.hub.v1.MessageR\amessage\"<\n" +
	"\x11BroadcastResponse\x12'\n" +
	"\x0frecipient_count\x18\x01 \x01(\x05R\x0erecipientCount2\x9c\x01\n" +
	"\n" +
	"HubService\x12@\n" +
	"\x05Route\x12\x1a.talos.hub.v1.RouteRequest\x1a\x1b.talos.hub.v1.RouteResponse\x12L\n" +
	"\tBroadcast\x12\x1e.talos.hub.v1.BroadcastRequest\x1a\x1f.talos.hub.v1.BroadcastResponseB$Z\"Talos/api/proto/talos/hub/v1;hubpbb\x06proto3"

var (
	file_api_proto_talos_hub_v1_hub_proto_rawDescOnce sync.Once
	file_api_proto_talos_hub_v1_hub_proto_rawDescData []byte
)

func file_api_proto_talos_hub_v1_hub_proto_rawDescGZIP() []byte {
	file_api_proto_talos_hub_v1_hub_proto_rawDescOnce.Do(func() {
		file_api_proto_talos_hub_v1_hub_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_talos_hub_v1_hub_proto_rawDesc), len(file_api_proto_talos_hub_v1_hub_proto_rawDesc)))
	})
	return file_api_proto_talos_hub_v1_hub_proto_rawDescData
}

var file_api_proto_talos_hub_v1_hub_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_talos_hub_v1_hub_proto_goTypes = []any{
	(*Message)(nil),           // 0: talos.hub.v1.Message
	(*RouteRequest)(nil),      // 1: talos.hub.v1.RouteRequest
	(*RouteResponse)(nil),     // 2: talos.hub.v1.RouteResponse
	(*BroadcastRequest)(nil),  // 3: talos.hub.v1.BroadcastRequest
	(*BroadcastResponse)(nil), // 4: talos.hub.v1.BroadcastResponse
}
var file_api_proto_talos_hub_v1_hub_proto_depIdxs = []int32{
	0, // 0: talos.hub.v1.RouteRequest.message:type_name -> talos.hub.v1.Message
	0, // 1: talos.hub.v1.RouteResponse.message:type_name -> talos.hub.v1.Message
	0, // 2: talos.hub.v1.BroadcastRequest.message:type_name -> talos.hub.v1.Message
	1, // 3: talos.hub.v1.HubService.Route:input_type -> talos.hub.v1.RouteRequest
	3, // 4: talos.hub.v1.HubService.Broadcast:input_type -> talos.hub.v1.BroadcastRequest
	2, // 5: talos.hub.v1.HubService.Route:output_type -> talos.hub.v1.RouteResponse
	4, // 6: talos.hub.v1.HubService.Broadcast:output_type -> talos.hub.v1.BroadcastResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_talos_hub_v1_hub_proto_init() }
func file_api_proto_talos_hub_v1_hub_proto_init() {
	if File_api_proto_talos_hub_v1_hub_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_talos_hub_v1_hub_proto_rawDesc), len(file_api_proto_talos_hub_v1_hub_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_talos_hub_v1_hub_proto_goTypes,
		DependencyIndexes: file_api_proto_talos_hub_v1_hub_proto_depIdxs,
		MessageInfos:      file_api_proto_talos_hub_v1_hub_proto_msgTypes,
	}.Build()
	File_api_proto_talos_hub_v1_hub_proto = out.File
	file_api_proto_talos_hub_v1_hub_proto_goTypes = nil
	file_api_proto_talos_hub_v1_hub_proto_depIdxs = nil
}
