#!/usr/bin/env bash
# Isolate npm node_modules trees from the Talos Go module: each Packages/**/node_modules
# directory gets a nested go.mod so Go does not treat third-party .go files (e.g. flatted)
# as package Talos/... and so paths with spaces under Packages/ do not break go mod tidy.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if [[ ! -d Packages ]]; then
  exit 0
fi

while IFS= read -r -d '' dir; do
  modfile="${dir}/go.mod"
  if [[ -f "$modfile" ]]; then
    continue
  fi
  # Stable unique module path from absolute path (no spaces in module path).
  hash=$(printf '%s' "$dir" | sha256sum | awk '{print $1}')
  module="talos.local/nm.${hash}"
  cat >"$modfile" <<EOF
module ${module}

go 1.24.0

// Generated by scripts/ensure-npm-go-modules.sh — keeps npm dependencies out of the Talos module.
EOF
done < <(find Packages -type d -name node_modules -print0 2>/dev/null)
