// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {packages} from '../models';

export function ApplyUpdateFromArtifactURL(arg1:string):Promise<string>;

export function BroadcastMessage(arg1:string,arg2:string,arg3:string):Promise<number>;

export function CheckForUpdates(arg1:string):Promise<Array<main.UpdateEntryView>>;

export function DefaultUpdateChannelURL():Promise<string>;

export function DenyPermission(arg1:string,arg2:string):Promise<void>;

export function DevelopmentFeaturesEnabled():Promise<boolean>;

export function GetDeveloperMode():Promise<boolean>;

export function GetInstalledApps():Promise<Array<main.AppManifestView>>;

export function GetLogCatalog():Promise<Record<string, string>>;

export function GetRuntimeInfo():Promise<Record<string, any>>;

export function GetStartupLaunchpad():Promise<main.AppManifestView>;

export function GetStoreApps():Promise<Array<main.AppManifestView>>;

export function GetThemes():Promise<Array<main.ThemeInfo>>;

export function GrantPermission(arg1:string,arg2:string):Promise<void>;

export function HostPostToIframe(arg1:string,arg2:string,arg3:string):Promise<void>;

export function HubSocketURL():Promise<string>;

export function IframePostToHost(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ImportTrustedPublisherKey(arg1:string,arg2:string):Promise<void>;

export function InstallPackageFromGitHub(arg1:string,arg2:string,arg3:string):Promise<string>;

export function InstallPackageFromURL(arg1:string):Promise<string>;

export function InstallPackageFromZipPath(arg1:string):Promise<string>;

export function ListPackages():Promise<Record<string, packages.PackageInfo>>;

export function ListPermissionAudit(arg1:number):Promise<Array<main.PermissionAuditEntry>>;

export function ListPermissionEntries():Promise<Array<main.PermissionEntry>>;

export function ListRepositoryPackages():Promise<Array<main.RemotePackageDescriptor>>;

export function ListTrustedPublisherKeyNames():Promise<Array<string>>;

export function LoadAppState(arg1:string):Promise<Array<number>>;

export function LoadAppStateBase64(arg1:string):Promise<string>;

export function LoadAppStateText(arg1:string):Promise<string>;

export function LoadUserPrefs():Promise<main.UserPrefs>;

export function PackageLocalHTTP(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.PackageLocalHTTPResponse>;

export function ParanoidPackageTrust():Promise<boolean>;

export function PickZipAndInstall():Promise<string>;

export function ReadLogTail(arg1:string,arg2:number):Promise<string>;

export function ReadScopedText(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RequestPermission(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function RequestPermissionDecision(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ResolveScopedPath(arg1:string,arg2:string):Promise<string>;

export function RevokePermission(arg1:string,arg2:string):Promise<void>;

export function RouteMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function RunningPackageIDs():Promise<Array<string>>;

export function SaveAppState(arg1:string,arg2:Array<number>):Promise<void>;

export function SaveAppStateBase64(arg1:string,arg2:string):Promise<void>;

export function SaveAppStateText(arg1:string,arg2:string):Promise<void>;

export function SaveUserPrefs(arg1:main.UserPrefs):Promise<void>;

export function SetDeveloperMode(arg1:boolean):Promise<void>;

export function StartPackage(arg1:string):Promise<void>;

export function StopPackage(arg1:string):Promise<void>;

export function WriteScopedText(arg1:string,arg2:string,arg3:string):Promise<void>;
