// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {packages} from '../models';

export function BroadcastMessage(arg1:string,arg2:string,arg3:string):Promise<number>;

export function DenyPermission(arg1:string,arg2:string):Promise<void>;

export function GrantPermission(arg1:string,arg2:string):Promise<void>;

export function HostPostToIframe(arg1:string,arg2:string,arg3:string):Promise<void>;

export function HubSocketURL():Promise<string>;

export function IframePostToHost(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListPackages():Promise<Record<string, packages.PackageInfo>>;

export function LoadAppState(arg1:string):Promise<Array<number>>;

export function LoadAppStateBase64(arg1:string):Promise<string>;

export function LoadAppStateText(arg1:string):Promise<string>;

export function RequestPermission(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function RequestPermissionDecision(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ResolveScopedPath(arg1:string,arg2:string):Promise<string>;

export function RouteMessage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function RunningPackageIDs():Promise<Array<string>>;

export function SaveAppState(arg1:string,arg2:Array<number>):Promise<void>;

export function SaveAppStateBase64(arg1:string,arg2:string):Promise<void>;

export function SaveAppStateText(arg1:string,arg2:string):Promise<void>;

export function StartPackage(arg1:string):Promise<void>;

export function StopPackage(arg1:string):Promise<void>;
