// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BroadcastMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['BroadcastMessage'](arg1, arg2, arg3);
}

export function DenyPermission(arg1, arg2) {
  return window['go']['main']['App']['DenyPermission'](arg1, arg2);
}

export function GrantPermission(arg1, arg2) {
  return window['go']['main']['App']['GrantPermission'](arg1, arg2);
}

export function HostPostToIframe(arg1, arg2, arg3) {
  return window['go']['main']['App']['HostPostToIframe'](arg1, arg2, arg3);
}

export function HubSocketURL() {
  return window['go']['main']['App']['HubSocketURL']();
}

export function IframePostToHost(arg1, arg2, arg3) {
  return window['go']['main']['App']['IframePostToHost'](arg1, arg2, arg3);
}

export function ListPackages() {
  return window['go']['main']['App']['ListPackages']();
}

export function LoadAppState(arg1) {
  return window['go']['main']['App']['LoadAppState'](arg1);
}

export function LoadAppStateBase64(arg1) {
  return window['go']['main']['App']['LoadAppStateBase64'](arg1);
}

export function LoadAppStateText(arg1) {
  return window['go']['main']['App']['LoadAppStateText'](arg1);
}

export function RequestPermission(arg1, arg2, arg3) {
  return window['go']['main']['App']['RequestPermission'](arg1, arg2, arg3);
}

export function RequestPermissionDecision(arg1, arg2, arg3) {
  return window['go']['main']['App']['RequestPermissionDecision'](arg1, arg2, arg3);
}

export function ResolveScopedPath(arg1, arg2) {
  return window['go']['main']['App']['ResolveScopedPath'](arg1, arg2);
}

export function RouteMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RouteMessage'](arg1, arg2, arg3, arg4);
}

export function RunningPackageIDs() {
  return window['go']['main']['App']['RunningPackageIDs']();
}

export function SaveAppState(arg1, arg2) {
  return window['go']['main']['App']['SaveAppState'](arg1, arg2);
}

export function SaveAppStateBase64(arg1, arg2) {
  return window['go']['main']['App']['SaveAppStateBase64'](arg1, arg2);
}

export function SaveAppStateText(arg1, arg2) {
  return window['go']['main']['App']['SaveAppStateText'](arg1, arg2);
}

export function StartPackage(arg1) {
  return window['go']['main']['App']['StartPackage'](arg1);
}

export function StopPackage(arg1) {
  return window['go']['main']['App']['StopPackage'](arg1);
}
